import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { getServerUser } from "@/utils/users/server";
import Navbar from "@/components/navbar";
import Footer from "@/components/pages/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getServerUser();
  // const credits = await fetch(`${process.env.NEXT_PUBLIC_URL}/api/credits`);
  // const creditsData = await credits.json();
  // console.log(creditsData);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar isLoggedIn={!!user} user={user!} />
        <main>{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
